name: Rust

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron:  '45 5,17 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Build with simd
      run: cargo build --features "simd" --verbose
    - name: Build
      run: cargo build --verbose
    - name: download test model
      run: wget -c -O vectors.bin 'https://www.dropbox.com/s/y4ls6yd4k0wbzhp/vectors.bin?dl=0'
    - name: Test with simd
      run: cargo test --features "simd" --verbose
    - name: Test
      run: cargo test --verbose